version: "3"

env:
  PROJECT_PKG: app

  BINARY_NAME: zabraPassChangerMulti
  BUILD_DIR: __dist
  BUILD_FILE: "{{.BUILD_DIR}}/{{.BINARY_NAME}}.exe"

  LDFLAGS: -ldflags="-s -w"

tasks:
  build:
    desc: Build the go binary.
    cmds:
      - go build -v {{.LDFLAGS}} -o {{.BUILD_FILE}}
      #- upx --best {{.RELEASE_FILE}}
    #ignore_error: true
